flondr_laravel/routes/web.php
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');

	Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
	Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'gerai.delete','uses' => 'GeraiController@destroy'));
	Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'gerai.featured','uses' => 'GeraiController@featured'));
	Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');
	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');
	
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'cctv.delete','uses' => 'CCTVController@destroy'));

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'portfolio.delete','uses' => 'PortfolioController@destroy'));

	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');
	
	Route::resource('vrs-admin/dailycp', 'DailyCPController');

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'rss.api.getall','uses' => 'RssController@getAllAjax'));
	Route::get('vrs-admin/rss/{rss}/delete',array('as'=> 'rss.delete','uses' => 'RssController@destroy'));
	Route::resource('vrs-admin/rss', 'RssController');

	Route::get('vrs-admin/social/{social}/delete',array('as'=> 'social.delete','uses' => 'SocialController@destroy'));
	Route::resource('vrs-admin/social', 'SocialController');

	Route::get('vrs-admin/comment/{comment}/delete',array('as'=> 'comment.delete','uses' => 'CommentController@destroy'));
	Route::get('vrs-admin/comment/{comment}/approve/{on}',array('as'=> 'comment.approve','uses' => 'CommentController@approve'));
	Route::resource('vrs-admin/comment','CommentController');

	Route::get('vrs-admin/typeclub/{id}/delete',array('as'=> 'typeclub.delete','uses' => 'TypeClubController@destroy'));
	Route::resource('vrs-admin/typeclub','TypeClubController');

	Route::get('vrs-admin/portfoliocategory/getAllAjax',array('as' => 'portfoliocategory.api.getall','uses' => 'PortfolioCategoryController@getAllAjax'));

	//Route::get('vrs-admin/notification/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/notification/create',array('as'=> 'notification.create','uses' => 'NotificationController@create'));
	Route::resource('vrs-admin/notification', 'NotificationController');
	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	
	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'file.delete','uses' => 'FileController@destroy'));
	Route::get('vrs-admin/file/featured/{id}', array('as' => 'file.featured','uses' => 'FileController@featured'));
	Route::resource('vrs-admin/file', 'FileController');

	Route::get('vrs-admin/video/getMedia/{name}','VideoController@getMedia');
	Route::get('vrs-admin/video/{video}/delete',array('as'=> 'video.delete','uses' => 'VideoController@destroy'));
	Route::get('vrs-admin/video/featured/{id}', array('as' => 'video.featured','uses' => 'VideoController@featured'));
	Route::resource('vrs-admin/video', 'VideoController');

	Route::any('/imglist', ['as'=>'imglist', 'uses'=>'FileBrowserController@imageList']);
		//Image upload

		Route::any('/upload', [ 'uses' =>'FileBrowserController@index']);
});

Route::get('read/{id}', 'PostController@show');
Route::get('/map', 'HomeController@map');
Route::post('/adukan', ['as' => 'home.adukan', 'uses' => 'HomeController@adukan']);

Route::get('post/search', 'PostController@search');
// Auth::routes();
Route::group(['middleware' => ['web']], function() {

// Login Routes...
    Route::get('flondr/backend/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('flondr/backend/', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

// Registration Routes...
    Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

// Password Reset Routes...
    Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
});

Route::get('auth/logout', function(){

flondr_laravel/app/Http/Controllers/SoalController.php
<?php namespace App\Http\Controllers;
use App\Http\Controllers\BasicController;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\SoalRequest;
use Illuminate\Http\Request;
use App\Soal;
use Session;
use DB;
use Input;
class SoalController extends BasicController {
	public function index(){
		$data['content'] = DB::table('ms_soal')->orderBy('id', 'desc')->get();
		$data['ujian'] = DB::table('ms_ujian')->get();
		return view('page.soal.index',compact('data'));
	}
	public function store(SoalRequest $request)
	{
		//$data = soal::create($request->all());
		$data = DB::table('ms_soal')->insert([
				'ms_ujian_id' => $request->ujian,
				'pertanyaan' => $request->pertanyaan,
				'jawaban_a' => $request->jawaban_a,
				'jawaban_b' => $request->jawaban_b,
				'jawaban_c' => $request->jawaban_c,
				'jawaban_d' => $request->jawaban_d,
				'jawaban_benar' => $request->jawaban_benar,
				'ms_media_id' => $request->ms_media_id
			]);
		/*$log = array();
		$log['action'] = 'insert';
		$log['name'] = $request->input('title');
		$data->logs()->save($this->log($log));*/

		Session::flash('success','Data berhasil ditambahkan');
		return redirect()->route('vrs-admin.soal.index');
	}

	public function edit($id)
	{
		$data['ujian'] = DB::table('ms_ujian')->get();
		$data['content'] = DB::table('ms_soal')->where('id', $id)->first();
		return view('page.soal.edit',compact('data'));
	}

	public function Update(SoalRequest $request, $id){
		//dd(Input::all());
		DB::table('ms_soal')
			->where('id', $id)
			->update([
				'ms_ujian_id' => $request->ujian,
				'pertanyaan' => $request->pertanyaan,
				'jawaban_a' => $request->jawaban_a,
				'jawaban_b' => $request->jawaban_b,
				'jawaban_c' => $request->jawaban_c,
				'jawaban_d' => $request->jawaban_d,
				'jawaban_benar' => $request->jawaban_benar,
				'ms_media_id' => $request->ms_media_id
			]);

		Session::flash('success','Data berhasil diperbarui');
		return redirect()->route('vrs-admin.soal.index');
	}

	public function Destroy($id){
		DB::table('ms_soal')->where('id', $id)->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.soal.index');
	}
}

flondr_laravel/resources/views/page/soal/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Edit Baru
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['SoalController@update',$data['content']->id], 'method' => 'PATCH')) !!}
					@include('page.soal.form',['buttonSubmit' => 'Perbarui'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@endsection

@section('custom-footer')
@include('page.scripts.media')
@stop

flondr_laravel/resources/views/page/soal/form.blade.php
					<div class="form-group">
						{!! Form::label('ms_media_id','Gambar : ') !!}
						<a href="javascript:void(0)" class="btn btn-default" onclick="setFeaturedImage()">Pilih Media</a>
						<div class="col-md-12" id="featuredImage">
						</div>
						{!! Form::hidden('ms_media_id',null, ['class' => 'form-control','id' => 'ms_media_id']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('pertanyaan','Pertanyaan : ') !!}
						{!! Form::textarea('pertanyaan',null, ['class' => 'form-control','rows'=>'3']) !!}
					</div>
					<hr>
					<div class="form-group">
						{!! Form::label('jawaban_a','Pilihan Jawaban A : ') !!}
						{!! Form::text('jawaban_a',null, ['class' => 'form-control', 'required']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('jawaban_b','Pilihan Jawaban  B: ') !!}
						{!! Form::text('jawaban_b',null, ['class' => 'form-control', 'required']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('jawaban_c','Pilihan Jawaban  C: ') !!}
						{!! Form::text('jawaban_c',null, ['class' => 'form-control', 'required']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('jawaban_d','Pilihan Jawaban  D: ') !!}
						{!! Form::text('jawaban_d',null, ['class' => 'form-control', 'required']) !!}
					</div>
					<hr>
					<div class="form-group">
						{!! Form::label('jawaban_benar','Jawaban Benar: ') !!}
						{!! Form::select('jawaban_benar', [
							'a' => 'Jawaban A',
							'b' => 'Jawaban B',
							'c' => 'Jawaban C',
							'd' => 'Jawaban D',
						], null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						<?php
						$ujianList = [];
						foreach ($data['ujian'] as $key => $value) {
							$ujianList[$value->id] = $value->title;
						}
						?>
						{!! Form::label('ujian','Untuk Ujian : ') !!}
						{!! Form::select('ujian', $ujianList, null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::submit($buttonSubmit,['class' => 'btn btn-info']) !!}
					</div>

flondr_laravel/resources/views/page/soal/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						SOAL
					</h3>
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<div class="row">
						<div class="col-md-3">
							<h5>Tambah Soal Baru</h5>
							{!! Form::open(array('route' => 'vrs-admin.soal.store', 'method' => 'post')) !!}
							<?php 
							$arrsoal = array();
							$arrsoal[0] = 'Tidak Ada';
							foreach($data['content'] as $row)
							{
								$arrsoal[$row->id] = $row->pertanyaan;
							}
							?>
							@include('page.soal.form',['buttonSubmit' => 'Tambah','arrsoal' => $arrsoal, 'ujian' => $data['ujian']])
							{!! Form::close()!!}
						</div>
						<div class="col-md-9">
							<div class="row">

							</div>
							<table class="table" id="dataTables">
								<thead>
									<tr>
										<th>&nbsp;</th>
										<th>Pertanyaan</th>
										<th>Jawaban</th>
									</tr>
								</thead>
								<tbody>
									@foreach($data['content'] as $row)
									<tr>
										<td>&nbsp;</td>
										<td>
											{{ $row->pertanyaan }}
											<div class="action-post-hover">
												<a href="{{route('vrs-admin.soal.edit',[ $row->id ])}}">edit</a>
												<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{{ URL::route('vrs-admin.soal.delete',[ $row->id ]) }}" style="color:red;">trash</a>
											</div>
										</td>
										<td>
											@if($row->jawaban_benar == 'a')
												{{ $row->jawaban_a}}
											@elseif($row->jawaban_benar == 'b')
												{{ $row->jawaban_b}}
											@elseif($row->jawaban_benar == 'c')
												{{ $row->jawaban_c}}
											@elseif($row->jawaban_benar == 'd')
												{{ $row->jawaban_d}}
											@endif
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/chartjs/Chart.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
</script>
@include('page.scripts.media')
@stop